### ISSUE TITLE
RSV: Compare locations plot stuck on y-axis

### ISSUE THREAD

**Issue by chan-solo** [vector-engineering/covidcg#550] opened 2022-06-03 02:40 UTC

**Comment by chan-solo** [comment] 2022-06-28 15:28
this one is I think the most urgent to fix

**Comment by atc3** [comment] 2022-09-14 14:39
Should be addressed by #568 (v2.7.0-rc3). We can reopen if it's still an issue but so far I'm unable to reproduce

**Closed by atc3** 2022-09-14 14:39 UTC
