### ISSUE TITLE
Nucleotide Position Shift of 1 in downloaded File

### ISSUE THREAD

**Issue by roman-at-github** [vector-engineering/covidcg#271] opened 2021-02-08 18:50 UTC
When downloading the data of SNVs the nucleotide positions of variants shifts 1 position higher than the information that is provided in the  summary table of the web browser version. The web browser information seems to be right when compared with your [reference sequence](https://www.ncbi.nlm.nih.gov/nuccore/MN996528). 

Here are screenshots of the browser summary table and corresponding downloaded data with one specific position highlighted for readability:
![glitch1](https://user-images.githubusercontent.com/45998792/107267117-bdd46380-6a46-11eb-9d04-5b439d90e574.PNG)
![glitch2](https://user-images.githubusercontent.com/45998792/107267130-c2008100-6a46-11eb-9fed-cd98dac77ed5.png)

**Comment by atc3** [comment] 2021-02-09 13:56
Thanks for bring this to our attention – I'll investigate and let you know when it's fixed

**Comment by EricFournier3** [comment] 2021-02-10 19:04
Thanks Albert. I also observed this shift

**Comment by atc3** [comment] 2021-02-10 22:00
I've pushed a fix for this bug in the latest version of the site (v1.5.1). Can you confirm that the issue is fixed?

**Comment by EricFournier3** [comment] 2021-02-11 03:08
Thanks Albert, i did the merge and it works for me.

**Comment by roman-at-github** [comment] 2021-02-12 08:49
It's working, thank you for the swift fix!

**Closed** 2021-02-12 08:50 UTC
